'use client';

import { useEffect, useRef, useState } from 'react';
import { useTranslations, useLocale } from 'next-intl';
import Link from '@/i18n/navigation';
import { useCustomerAssistant } from '@/shared/client/providers/CustomerAssistantProvider';
import { customerPath } from '@/shared/customer-assistant-policy';
import type { ProductSummary } from '@/shared/types/product';
import ActionCard from './ActionCard';

const STARTERS = [
  { icon: '⌕', title: 'findTitle', prompt: 'findPrompt', deep: false },
  { icon: '◎', title: 'compareTitle', prompt: 'comparePrompt', deep: true },
  { icon: '▤', title: 'ordersTitle', prompt: 'ordersPrompt', deep: false },
  { icon: '✎', title: 'draftTitle', prompt: 'draftPrompt', deep: false },
] as const;

// Small safe formatter: no HTML or remote/model-controlled links are rendered.
function Answer({ text }: { text: string }) {
  return (
    <div className="agent-answer">
      {text.split('\n').map((line, i) => (
        <p key={i}>
          {line.split(/(\[[^\]]+\]\([^\s)]+\)|\*\*[^*]+\*\*)/g).map((part, j) => {
            const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
            if (link) {
              const path = customerPath(link[2]);
              return path ? (
                <Link key={j} href={path}>
                  {link[1]}
                </Link>
              ) : (
                <span key={j}>{link[1]}</span>
              );
            }
            if (part.startsWith('**') && part.endsWith('**')) return <strong key={j}>{part.slice(2, -2)}</strong>;
            return <span key={j}>{part.replace(/^#{1,4}\s/, '')}</span>;
          })}
        </p>
      ))}
    </div>
  );
}
function ProductCard({ product }: { product: ProductSummary }) {
  const agent = useCustomerAssistant();
  const t = useTranslations('assistant');
  const locale = useLocale();
  const catalog = useTranslations('catalog');
  const stockLabels = { inStock: catalog('inStock'), soldOut: catalog('soldOut') };
  return (
    <article className="agent-product-card">
      <Link href={`/shop/product/${product.id}`} className="agent-product-link">
        {/* Public catalog images already used by the storefront; never URLs generated by the model. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={product.imageUrl} alt={product.name} loading="lazy" />
        <span>
          <small>{product.brandName}</small>
          <strong>{product.name}</strong>
          <b>
            {new Intl.NumberFormat(locale === 'en' ? 'en-US' : 'vi-VN', { style: 'currency', currency: 'VND' }).format(
              product.salePrice ?? product.price,
            )}
          </b>
          <small>
            {product.stock > 0 ? stockLabels.inStock : stockLabels.soldOut}
            {product.reviewCount ? ` · ${Number(product.rating).toFixed(1)} ★ (${product.reviewCount})` : ''}
          </small>
        </span>
      </Link>
      <div className="agent-product-buttons">
        <button
          disabled={agent.busy || product.stock <= 0}
          onClick={() => {
            void agent.send(t('addPrompt', { id: product.id, name: product.name }));
          }}
        >
          {t('addToBag')}
        </button>
        <button
          disabled={agent.busy}
          onClick={() => {
            agent.setResearch(true);
            agent.setPrompt(t('researchProductPrompt', { id: product.id, name: product.name }));
          }}
        >
          {t('researchProduct')}
        </button>
      </div>
    </article>
  );
}
export default function AssistantConversation({ full = false }: { full?: boolean }) {
  const agent = useCustomerAssistant();
  const t = useTranslations('assistant');
  const log = useRef<HTMLDivElement>(null);
  const input = useRef<HTMLTextAreaElement>(null);
  const [following, setFollowing] = useState(true);
  const [completed, setCompleted] = useState(false);
  const latestUser = agent.messages.map((m) => m.role).lastIndexOf('user');
  useEffect(() => {
    if (following && log.current) log.current.scrollTop = log.current.scrollHeight;
  }, [agent.messages, agent.busy, following]);
  useEffect(() => {
    if (agent.prompt) input.current?.focus();
  }, [agent.prompt]);
  return (
    <div className={`agent-conversation ${full ? 'agent-conversation-full' : ''}`}>
      <div
        className="agent-log"
        ref={log}
        onScroll={(e) => {
          const el = e.currentTarget;
          setFollowing(el.scrollHeight - el.clientHeight - el.scrollTop < 90);
        }}
      >
        {agent.messages.length === 0 && (
          <div className="agent-welcome">
            <span className="agent-welcome-mark" aria-hidden="true">
              ✦
            </span>
            <span className="agent-eyebrow">{t('welcomeEyebrow')}</span>
            <h2>{t('welcomeTitle')}</h2>
            <p>{t('welcomeNote')}</p>
            <div className="agent-starters">
              {STARTERS.map((s) => (
                <button
                  key={s.title}
                  onClick={() => {
                    agent.setResearch(s.deep);
                    agent.setPrompt(t(s.prompt));
                  }}
                >
                  <span aria-hidden="true">{s.icon}</span>
                  <strong>{t(s.title)}</strong>
                  <span aria-hidden="true">↗</span>
                </button>
              ))}
            </div>
            <p className="agent-welcome-note">{t('welcomeExample')}</p>
          </div>
        )}
        <div
          className="agent-messages"
          role="log"
          aria-label={t('conversationLabel')}
          aria-live="polite"
          aria-relevant="additions"
        >
          {agent.messages.map((message, index) => (
            <article key={message.id} className={`agent-message agent-message-${message.role}`}>
              <div className="agent-message-label">
                {message.role === 'user'
                  ? t('you')
                  : message.reply?.research
                    ? `✦ ${t('name')} · ${t('researchLabel')}`
                    : `✦ ${t('name')}`}
              </div>
              <Answer text={message.text} />
              {!!message.reply?.products.length && (
                <div className="agent-products">
                  {message.reply.products.map((p) => (
                    <ProductCard key={p.id} product={p} />
                  ))}
                </div>
              )}
              {!!message.reply?.sources.length && (
                <details className="agent-sources">
                  <summary>{t('sources', { count: message.reply.sources.length })}</summary>
                  <div>
                    {message.reply.sources.map((s) => (
                      <Link key={s.path} href={s.path}>
                        {s.label} ↗
                      </Link>
                    ))}
                  </div>
                </details>
              )}
              {message.reply?.actions.map((action, i) => (
                <ActionCard key={`${message.id}-${i}`} action={action} obsolete={index < latestUser} />
              ))}
            </article>
          ))}
        </div>
        {agent.busy && (
          <div className="agent-thinking" role="status">
            <span className="agent-thinking-dots">● ● ●</span>
            <strong>{agent.research ? t('researching') : t('thinking')}</strong>
            <small>{agent.research ? t('researchingNote') : t('thinkingNote')}</small>
          </div>
        )}
        {agent.error && (
          <div className="agent-error-box" role="alert">
            <p>{agent.error}</p>
            <div>
              <button
                onClick={() => {
                  setFollowing(true);
                  void agent.send(agent.prompt);
                }}
                disabled={agent.busy}
              >
                {t('retry')}
              </button>
              <Link href="/shop" onClick={agent.close}>
                {t('explore')}
              </Link>
              <Link href="/contact" onClick={agent.close}>
                {t('contact')}
              </Link>
            </div>
          </div>
        )}
      </div>
      {!following && (
        <button
          className="agent-new-message"
          onClick={() => {
            setFollowing(true);
            if (log.current) log.current.scrollTop = log.current.scrollHeight;
          }}
        >
          {t('newMessages')}
        </button>
      )}
      <div className="agent-composer">
        <div className="agent-composer-tools">
          <label className={`agent-research-toggle ${agent.research ? 'is-active' : ''}`} title={t('researchHint')}>
            <input
              type="checkbox"
              checked={agent.research}
              disabled={agent.busy}
              onChange={(e) => agent.setResearch(e.target.checked)}
            />
            {t('deepResearch')}
          </label>
          <button
            className="agent-text-button"
            disabled={agent.busy || !agent.messages.length}
            onClick={() => setCompleted(true)}
          >
            {t('newChat')}
          </button>
        </div>
        {completed && (
          <div className="agent-reset-confirm">
            <span>{t('clearQuestion')}</span>
            <button
              onClick={() => {
                agent.clear();
                setCompleted(false);
              }}
            >
              {t('clearChat')}
            </button>
            <button onClick={() => setCompleted(false)}>{t('keepChat')}</button>
          </div>
        )}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            setFollowing(true);
            void agent.send(agent.prompt);
          }}
          className="agent-input-wrap"
        >
          <textarea
            ref={input}
            aria-label={t('messageLabel')}
            placeholder={t('messagePlaceholder')}
            rows={2}
            maxLength={3000}
            value={agent.prompt}
            onChange={(e) => agent.setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
                e.preventDefault();
                if (!agent.busy) {
                  setFollowing(true);
                  void agent.send(agent.prompt);
                }
              }
            }}
          />
          <button
            className="agent-send"
            type="submit"
            disabled={agent.busy || !agent.prompt.trim()}
            aria-label={t('sendMessage')}
          >
            ↑
          </button>
        </form>
        <p className="agent-composer-note">{t('composerNote')}</p>
      </div>
    </div>
  );
}
