'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useCustomerAssistant } from '@/shared/client/providers/CustomerAssistantProvider';
import { customerPath } from '@/shared/customer-assistant-policy';
import type { ProductSummary } from '@/shared/types/product';
import { formatVND } from '@/shared/server/utils/utils';
import ActionCard from './ActionCard';

const STARTERS = [
  {
    icon: '⌕',
    title: 'Tìm món phù hợp',
    prompt: 'Giúp tôi tìm sản phẩm phù hợp với nhu cầu và ngân sách.',
    deep: false,
  },
  {
    icon: '◎',
    title: 'Nghiên cứu & so sánh',
    prompt: 'Tôi muốn nghiên cứu chuyên sâu và so sánh sản phẩm trong cửa hàng. Hãy hỏi tôi nhu cầu trước.',
    deep: true,
  },
  {
    icon: '▤',
    title: 'Hỗ trợ đơn hàng',
    prompt: 'Giúp tôi kiểm tra các đơn hàng gần đây và những thao tác tôi có thể làm.',
    deep: false,
  },
  {
    icon: '✎',
    title: 'Viết lời nhắn, đánh giá',
    prompt: 'Tôi muốn nhờ bạn soạn nội dung liên hệ hoặc đánh giá sản phẩm từ trải nghiệm của tôi.',
    deep: false,
  },
];

// Small safe formatter: no HTML or remote/model-controlled links are rendered.
function Answer({ text }: { text: string }) {
  return (
    <div className="agent-answer">
      {text.split('\n').map((line, i) => (
        <p key={i}>
          {line.split(/(\[[^\]]+\]\([^\s)]+\)|\*\*[^*]+\*\*)/g).map((part, j) => {
            const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
            if (link) {
              const path = customerPath(link[2]);
              return path ? (
                <Link key={j} href={path}>
                  {link[1]}
                </Link>
              ) : (
                <span key={j}>{link[1]}</span>
              );
            }
            if (part.startsWith('**') && part.endsWith('**')) return <strong key={j}>{part.slice(2, -2)}</strong>;
            return <span key={j}>{part.replace(/^#{1,4}\s/, '')}</span>;
          })}
        </p>
      ))}
    </div>
  );
}
function ProductCard({ product }: { product: ProductSummary }) {
  const agent = useCustomerAssistant();
  return (
    <article className="agent-product-card">
      <Link href={`/shop/product/${product.id}`} className="agent-product-link">
        {/* Public catalog images already used by the storefront; never URLs generated by the model. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={product.imageUrl} alt={product.name} loading="lazy" />
        <span>
          <small>{product.brandName}</small>
          <strong>{product.name}</strong>
          <b>{formatVND(product.salePrice ?? product.price)}</b>
          <small>
            {product.stock > 0 ? 'Còn hàng' : 'Hết hàng'}
            {product.reviewCount ? ` · ${Number(product.rating).toFixed(1)} ★ (${product.reviewCount})` : ''}
          </small>
        </span>
      </Link>
      <div className="agent-product-buttons">
        <button
          disabled={agent.busy || product.stock <= 0}
          onClick={() => {
            void agent.send(`Thêm 1 sản phẩm #${product.id} (${product.name}) vào giỏ giúp tôi.`);
          }}
        >
          Thêm vào giỏ
        </button>
        <button
          disabled={agent.busy}
          onClick={() => {
            agent.setResearch(true);
            agent.setPrompt(
              `Nghiên cứu kỹ sản phẩm #${product.id} (${product.name}), ưu nhược điểm, thông số và đánh giá trong cửa hàng.`,
            );
          }}
        >
          Tìm hiểu kỹ
        </button>
      </div>
    </article>
  );
}
export default function AssistantConversation({ full = false }: { full?: boolean }) {
  const agent = useCustomerAssistant();
  const log = useRef<HTMLDivElement>(null);
  const input = useRef<HTMLTextAreaElement>(null);
  const [following, setFollowing] = useState(true);
  const [completed, setCompleted] = useState(false);
  const latestUser = agent.messages.map((m) => m.role).lastIndexOf('user');
  useEffect(() => {
    if (following && log.current) log.current.scrollTop = log.current.scrollHeight;
  }, [agent.messages, agent.busy, following]);
  useEffect(() => {
    if (agent.prompt) input.current?.focus();
  }, [agent.prompt]);
  return (
    <div className={`agent-conversation ${full ? 'agent-conversation-full' : ''}`}>
      <div
        className="agent-log"
        ref={log}
        onScroll={(e) => {
          const el = e.currentTarget;
          setFollowing(el.scrollHeight - el.clientHeight - el.scrollTop < 90);
        }}
      >
        {agent.messages.length === 0 && (
          <div className="agent-welcome">
            <span className="agent-welcome-mark" aria-hidden="true">
              ✦
            </span>
            <span className="agent-eyebrow">TRỢ LÝ MUA SẮM CỦA BẠN</span>
            <h2>
              Bạn cần gì,
              <br />
              cứ hỏi Agent.
            </h2>
            <p>Từ chọn món phù hợp đến chăm sóc sau mua. Mình cùng bạn tìm hiểu và thực hiện ngay tại đây.</p>
            <div className="agent-starters">
              {STARTERS.map((s) => (
                <button
                  key={s.title}
                  onClick={() => {
                    agent.setResearch(s.deep);
                    agent.setPrompt(s.prompt);
                  }}
                >
                  <span aria-hidden="true">{s.icon}</span>
                  <strong>{s.title}</strong>
                  <span aria-hidden="true">↗</span>
                </button>
              ))}
            </div>
            <p className="agent-welcome-note">
              Bạn có thể bắt đầu với: “Tìm giày đi bộ dưới 1 triệu”, hoặc “So sánh hai sản phẩm này”.
            </p>
          </div>
        )}
        <div
          className="agent-messages"
          role="log"
          aria-label="Cuộc trò chuyện với Agent"
          aria-live="polite"
          aria-relevant="additions"
        >
          {agent.messages.map((message, index) => (
            <article key={message.id} className={`agent-message agent-message-${message.role}`}>
              <div className="agent-message-label">
                {message.role === 'user'
                  ? 'Bạn'
                  : message.reply?.research
                    ? '✦ Agent · Nghiên cứu sản phẩm'
                    : '✦ Agent'}
              </div>
              <Answer text={message.text} />
              {!!message.reply?.products.length && (
                <div className="agent-products">
                  {message.reply.products.map((p) => (
                    <ProductCard key={p.id} product={p} />
                  ))}
                </div>
              )}
              {!!message.reply?.sources.length && (
                <details className="agent-sources">
                  <summary>Nguồn trong cửa hàng · {message.reply.sources.length}</summary>
                  <div>
                    {message.reply.sources.map((s) => (
                      <Link key={s.path} href={s.path}>
                        {s.label} ↗
                      </Link>
                    ))}
                  </div>
                </details>
              )}
              {message.reply?.actions.map((action, i) => (
                <ActionCard key={`${message.id}-${i}`} action={action} obsolete={index < latestUser} />
              ))}
            </article>
          ))}
        </div>
        {agent.busy && (
          <div className="agent-thinking" role="status">
            <span className="agent-thinking-dots">● ● ●</span>
            <strong>
              {agent.research ? 'Đang nghiên cứu sản phẩm trong cửa hàng…' : 'Agent đang tìm thông tin phù hợp…'}
            </strong>
            <small>
              {agent.research
                ? 'Đọc thông số, đối chiếu lựa chọn và đánh giá của khách.'
                : 'Mình sẽ đưa ra gợi ý và các thao tác để bạn chọn.'}
            </small>
          </div>
        )}
        {agent.error && (
          <div className="agent-error-box" role="alert">
            <p>{agent.error}</p>
            <div>
              <button
                onClick={() => {
                  setFollowing(true);
                  void agent.send(agent.prompt);
                }}
                disabled={agent.busy}
              >
                Thử lại
              </button>
              <Link href="/shop" onClick={agent.close}>
                Xem sản phẩm
              </Link>
              <Link href="/contact" onClick={agent.close}>
                Liên hệ cửa hàng
              </Link>
            </div>
          </div>
        )}
      </div>
      {!following && (
        <button
          className="agent-new-message"
          onClick={() => {
            setFollowing(true);
            if (log.current) log.current.scrollTop = log.current.scrollHeight;
          }}
        >
          Xuống tin nhắn mới ↓
        </button>
      )}
      <div className="agent-composer">
        <div className="agent-composer-tools">
          <label
            className={`agent-research-toggle ${agent.research ? 'is-active' : ''}`}
            title="So sánh sâu dựa trên thông số và đánh giá trong cửa hàng"
          >
            <input
              type="checkbox"
              checked={agent.research}
              disabled={agent.busy}
              onChange={(e) => agent.setResearch(e.target.checked)}
            />
            ◎ Nghiên cứu chuyên sâu
          </label>
          <button
            className="agent-text-button"
            disabled={agent.busy || !agent.messages.length}
            onClick={() => setCompleted(true)}
          >
            Chat mới
          </button>
        </div>
        {completed && (
          <div className="agent-reset-confirm">
            <span>Xóa cuộc trò chuyện hiện tại?</span>
            <button
              onClick={() => {
                agent.clear();
                setCompleted(false);
              }}
            >
              Xóa chat
            </button>
            <button onClick={() => setCompleted(false)}>Giữ lại</button>
          </div>
        )}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            setFollowing(true);
            void agent.send(agent.prompt);
          }}
          className="agent-input-wrap"
        >
          <textarea
            ref={input}
            aria-label="Tin nhắn cho Agent"
            placeholder="Nói cho mình biết bạn đang cần gì…"
            rows={2}
            maxLength={3000}
            value={agent.prompt}
            onChange={(e) => agent.setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
                e.preventDefault();
                if (!agent.busy) {
                  setFollowing(true);
                  void agent.send(agent.prompt);
                }
              }
            }}
          />
          <button
            className="agent-send"
            type="submit"
            disabled={agent.busy || !agent.prompt.trim()}
            aria-label="Gửi tin nhắn"
          >
            ↑
          </button>
        </form>
        <p className="agent-composer-note">Agent gợi ý, bạn quyết định. Giá và tồn kho được kiểm tra khi thực hiện.</p>
      </div>
    </div>
  );
}
