import { test, expect } from '@playwright/test';
import { randomUUID } from 'crypto';
import path from 'path';
import fs from 'fs';
import { admin, hasAdmin, writesEnabled } from './helpers';
import en from '../src/messages/en.json';
import vi from '../src/messages/vi.json';

for (const locale of ['vi', 'en']) for (const width of [1440, 390]) {
  test(`${locale} ${width}: localized product creation, edit, visibility and deletion`, async ({ page }) => {
    test.skip(!hasAdmin || !writesEnabled || process.env.E2E_PRODUCT_FIXTURE !== 'dedicated_browser_test' ||
      !process.env.E2E_PRODUCT_DB_NAME?.endsWith('_test'), 'Requires explicitly selected disposable product fixture.');
    test.setTimeout(180000);
    page.setDefaultTimeout(15000);
    const messages = locale === 'en' ? en : vi, labels = messages.adminProducts;
    const key = randomUUID(), name = `Synthetic catalog ${key}`, sku = `UI-${key}`;
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 });
    expect((await page.request.post('/api/auth/login', { data: admin })).ok()).toBeTruthy();
    await page.goto(`/${locale}/admin/products/new`);
    await expect(page.getByRole('heading', { name: labels.create, exact: true })).toBeVisible();
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await expect(page.getByText(labels.validation.nameRequired, { exact: true })).toBeVisible();
    await page.getByLabel(labels.name, { exact: true }).fill(name);
    await page.getByLabel(labels.brand, { exact: true }).fill('Synthetic Gundam fixture');
    const categories = page.getByLabel(labels.category, { exact: true });
    await expect(categories.locator('option')).not.toHaveCount(1);
    const categoryId = await categories.locator('option').nth(1).getAttribute('value');
    await categories.selectOption(categoryId!);
    await page.getByLabel(messages.catalog.grade, { exact: true }).selectOption('HG');
    await page.getByLabel(messages.catalog.scale, { exact: true }).fill('1/144');
    await page.getByLabel(messages.catalog.modelCode, { exact: true }).fill(`GUNPLA-${key.slice(0, 8)}`);
    await page.getByLabel(messages.catalog.descriptionEn, { exact: true }).fill('Synthetic Gunpla inspection fixture, not a real sellable kit.');
    await page.getByLabel(messages.catalog.descriptionVi, { exact: true }).fill('Mô hình kiểm thử tổng hợp, không phải hàng bán thật.');
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await expect(page.getByText(labels.validation.mainImageRequired, { exact: true })).toBeVisible();
    await page.getByLabel(labels.chooseImage, { exact: false }).setInputFiles(path.resolve('public/images/catalog/strike-freedom-custom.webp'));
    await expect(page.getByRole('button', { name: labels.removeImage.replace('{label}', labels.mainImage), exact: true })).toBeVisible();
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await page.getByLabel(labels.sellingPrice, { exact: true }).fill('350000');
    await page.getByLabel(labels.importPrice, { exact: true }).fill('250000');
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await page.getByLabel(labels.stock, { exact: true }).fill('1');
    await page.getByLabel('SKU', { exact: true }).fill(sku);
    await page.getByRole('button', { name: labels.next, exact: true }).click();
    await expect(page.getByRole('heading', { name: labels.review, exact: true })).toBeVisible();
    const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/admin/products') && response.request().method() === 'POST');
    await page.getByRole('button', { name: labels.finish, exact: true }).click();
    const created = await createdResponse; expect(created.ok(), await created.text()).toBeTruthy();
    const product = (await created.json()).data;
    await page.waitForURL(`**/${locale}/admin/products`);
    const search = page.getByRole('textbox', { name: labels.search, exact: true });
    await search.fill(sku);
    await page.getByRole('button', { name: messages.dataTable.openRecord.replace('{id}', String(product.id)), exact: true }).click();
    await expect(page.getByLabel(labels.name, { exact: true })).toHaveValue(name);
    expect(product.grade).toBe('HG'); expect(product.scale).toBe('1/144'); expect(product.stock).toBe(1);
    const renamed = `${name} revised`;
    await page.getByLabel(labels.name, { exact: true }).fill(renamed);
    await page.getByRole('checkbox', { name: new RegExp(`^${labels.archived}`) }).check();
    const savedResponse = page.waitForResponse(response => response.url().endsWith(`/api/admin/products/${product.id}`) && response.request().method() === 'PUT');
    await page.getByRole('button', { name: labels.save, exact: true }).click();
    const saved = await savedResponse; expect(saved.ok(), await saved.text()).toBeTruthy();
    await expect(page.getByLabel(labels.name, { exact: true })).toHaveValue(renamed);
    expect((await saved.json()).data.isArchived).toBe(true);
    expect((await page.request.get(`/api/products/${product.id}`)).status()).toBe(404);
    const artifacts = path.resolve('../../.artifacts/model-universe/visual'); fs.mkdirSync(artifacts, { recursive: true });
    await page.screenshot({ path: path.join(artifacts, `${locale}-${width}-product-management.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    await page.getByRole('button', { name: labels.remove, exact: true }).click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button', { name: labels.deleteLabel, exact: true }).click();
    await page.waitForURL(`**/${locale}/admin/products`);
    expect((await page.request.get(`/api/admin/products/${product.id}`)).status()).toBe(404);
    expect(errors).toEqual([]);
  });
}
