import { test, expect } from '@playwright/test';
import fs from 'fs';
import { randomUUID } from 'crypto';
import path from 'path';
import { admin, customer, hasAdmin, hasCustomer, writesEnabled } from './helpers';
import en from '../src/messages/en.json';
import vi from '../src/messages/vi.json';

const artifacts = path.resolve('../../.artifacts/model-universe/visual');
for (const locale of ['vi', 'en']) {
  for (const device of [{ name: 'desktop', width: 1440, height: 1000 }, { name: 'mobile', width: 390, height: 844 }]) {
    test(`${locale} ${device.name}: signed custody, actual disbursement, redemption and handback`, async ({ page, browser }) => {
      test.skip(process.env.E2E_PAWN_FIXTURE !== 'dedicated_browser_test' || !hasAdmin || !hasCustomer || !writesEnabled, 'Requires the dedicated pawn browser database and its explicit test-only policy.');
      test.setTimeout(240000);
      const messages = locale === 'en' ? en : vi;
      const errors: string[] = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.setViewportSize(device);
      expect((await page.request.post('/api/auth/login', { data: customer })).ok()).toBeTruthy();
      await page.goto(`/${locale}/services/pawn`);
      await page.getByRole('button', { name: messages.pawn.newRequest, exact: true }).click();
      const modelName = `Browser contract fixture ${locale} ${device.name} ${randomUUID().slice(0, 8)}`;
      const fields = { name: modelName, modelCode: 'PAWN-CONTRACT-FIXTURE', version: 'Custom inspected model', boxCondition: 'No original box', accessories: 'Display stand', defects: 'Disclosed shield paint wear', repairHistory: 'Custom paint, no repairs reported' };
      for (const [key, value] of Object.entries(fields)) await page.getByLabel(messages.buyback.asset[key as keyof typeof messages.buyback.asset], { exact: true }).fill(value);
      await page.getByRole('combobox', { name: messages.buyback.asset.assemblyState, exact: true }).selectOption('painted');
      await page.getByLabel(messages.buyback.photos, { exact: true }).setInputFiles(['strike-freedom-custom.webp', 'strike-freedom-custom-side.webp', 'strike-freedom-custom-detail.webp'].map(name => path.resolve('public/images/catalog', name)));
      await expect(page.getByRole('button', { name: messages.common.submit, exact: true })).toBeEnabled();
      const creation = page.waitForResponse(response => response.url().endsWith('/api/pawn') && response.request().method() === 'POST');
      await page.getByRole('button', { name: messages.common.submit, exact: true }).click();
      const created = await creation;
      expect(created.ok()).toBeTruthy();
      const row = (await created.json()).data;
      const staffContext = await browser.newContext({ baseURL: process.env.E2E_BASE_URL || 'http://localhost:6050', viewport: device });
      const staff = await staffContext.newPage();
      staff.on('pageerror', error => errors.push(error.message));
      expect((await staff.request.post('/api/auth/login', { data: admin })).ok()).toBeTruthy();
      await staff.goto(`/${locale}/admin/pawn`);
      const reopen = async () => { await staff.reload(); await staff.getByRole('button').filter({ hasText: `#${row.id} ·` }).click(); };
      await staff.getByRole('button').filter({ hasText: `#${row.id} ·` }).click();
      const quote = staff.getByRole('form', { name: messages.pawn.quote, exact: true });
      await quote.getByLabel(messages.pawn.appraisal, { exact: true }).fill('2000000');
      await quote.getByLabel(messages.pawn.principal, { exact: true }).fill('1400000');
      await quote.getByLabel(messages.pawn.termDays, { exact: true }).fill('30');
      await quote.getByLabel(messages.pawn.details, { exact: true }).fill('Synthetic test agreement: 0.03% daily simple interest, completed days, ceil VND, two-day grace, stop on verified payment. No disposal authorization.');
      await quote.getByRole('combobox', { name: messages.pawn.disposalChoice, exact: true }).selectOption('no');
      await quote.getByRole('button', { name: messages.pawn.quote, exact: true }).click();
      await expect(staff.getByText(messages.pawn.terms, { exact: true })).toBeVisible();
      await page.reload();
      await page.getByRole('button').filter({ hasText: `#${row.id} ·` }).click();
      const accept = page.getByRole('form', { name: messages.pawn.accept, exact: true });
      await accept.getByRole('checkbox', { name: messages.pawn.termsAccepted, exact: true }).check();
      await accept.getByRole('button', { name: messages.pawn.accept, exact: true }).click();
      await expect(page.getByLabel(messages.pawn.uploadContract, { exact: true })).toBeVisible();
      fs.mkdirSync(artifacts, { recursive: true });
      const documentPage = await staffContext.newPage();
      await documentPage.setViewportSize({ width: 800, height: 700 });
      await documentPage.setContent('<main style="font:22px sans-serif;padding:50px"><h1>Model Universe — automated test fixture</h1><p>Not a real contract or legal signature.</p><p>Loan: 1,400,000 VND. Appraisal: 2,000,000 VND.</p><p>Term: 30 days. Interest: 0.03% / completed day.</p><p>Fixture customer signature: TEST COLLECTOR</p><p>Fixture staff signature: TEST ADMINISTRATOR</p><p>For disposable database verification only.</p></main>');
      const documentPath = path.join(artifacts, `pawn-contract-fixture-${locale}-${device.name}.png`);
      await documentPage.screenshot({ path: documentPath });
      await documentPage.close();
      await page.getByLabel(messages.pawn.uploadContract, { exact: true }).setInputFiles(documentPath);
      await expect(page.getByRole('button', { name: messages.pawn.attachContract, exact: true })).toBeEnabled();
      await page.getByRole('button', { name: messages.pawn.attachContract, exact: true }).click();
      await expect(page.getByLabel(messages.pawn.uploadContract, { exact: true })).toHaveCount(0);
      await reopen();
      const contract = staff.getByRole('form', { name: messages.pawn.confirmContract, exact: true });
      await contract.getByLabel(messages.pawn.contractReference, { exact: true }).fill(`BROWSER-CONTRACT-${row.id}`);
      await contract.getByRole('checkbox', { name: messages.pawn.signatureVerified, exact: true }).check();
      await contract.getByRole('button', { name: messages.pawn.confirmContract, exact: true }).click();
      const custody = staff.getByRole('form', { name: messages.pawn.receiveAsset, exact: true });
      await custody.getByLabel(messages.pawn.custodyReference, { exact: true }).fill(`BROWSER-CUSTODY-${row.id}`);
      await custody.getByLabel(messages.pawn.details, { exact: true }).fill('Synthetic fixture physical handover and disclosed condition verified.');
      await custody.getByRole('checkbox', { name: messages.pawn.handoverVerified, exact: true }).check();
      await custody.getByRole('checkbox', { name: messages.pawn.conditionMatches, exact: true }).check();
      await custody.getByRole('button', { name: messages.pawn.receiveAsset, exact: true }).click();
      const disbursement = staff.getByRole('form', { name: messages.pawn.disbursement, exact: true });
      await disbursement.getByLabel(messages.pawn.paymentReference, { exact: true }).fill(`BROWSER-DISBURSE-${row.id}`);
      await disbursement.getByLabel(messages.pawn.details, { exact: true }).fill('Synthetic fixture executed principal transfer, verified separately from custody.');
      await disbursement.getByRole('checkbox', { name: messages.pawn.moneyVerified, exact: true }).check();
      await disbursement.getByRole('button', { name: messages.pawn.disbursement, exact: true }).click();
      await expect(staff.getByText(messages.pawn.redemptionEstimate, { exact: true })).toBeVisible();
      await page.reload();
      await page.getByRole('button').filter({ hasText: `#${row.id} ·` }).click();
      await expect(page.getByText(messages.pawn.redemptionEstimate, { exact: true })).toBeVisible();
      await page.locator('#pawn-detail').screenshot({ path: path.join(artifacts, `${locale}-${device.name}-pawn-active.png`) });
      const redemption = staff.getByRole('form', { name: messages.pawn.redemption, exact: true });
      await redemption.getByLabel(messages.pawn.paymentReference, { exact: true }).fill(`BROWSER-REDEMPTION-${row.id}`);
      await redemption.getByLabel(messages.pawn.details, { exact: true }).fill('Synthetic same-day repayment; completed-day interest remains zero.');
      await redemption.getByRole('checkbox', { name: messages.pawn.moneyVerified, exact: true }).check();
      await redemption.getByRole('button', { name: messages.pawn.redemption, exact: true }).click();
      const handback = staff.getByRole('form', { name: messages.pawn.handback, exact: true });
      await handback.getByLabel(messages.pawn.details, { exact: true }).fill('Synthetic actual asset handback to its owner, separately verified after repayment.');
      await handback.getByRole('checkbox', { name: messages.pawn.handoverVerified, exact: true }).check();
      await handback.getByRole('button', { name: messages.pawn.handback, exact: true }).click();
      await expect(handback).toHaveCount(0);
      await staff.locator('#pawn-detail').screenshot({ path: path.join(artifacts, `${locale}-${device.name}-staff-pawn-returned.png`) });
      await page.reload();
      await page.getByRole('button').filter({ hasText: `#${row.id} ·` }).click();
      const payload = await (await page.request.get(`/api/pawn/${row.id}`)).json();
      expect(payload.status).toBe('returned');
      expect(payload.payments.map((payment: { amountVnd: number }) => payment.amountVnd)).toEqual([1400000, 1400000]);
      expect(payload.estimate.remainingVnd).toBe(0);
      expect(payload.handbackAt).toBeTruthy();
      expect(payload.productId).toBeNull();
      await page.locator('#pawn-detail').screenshot({ path: path.join(artifacts, `${locale}-${device.name}-pawn-returned.png`) });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      expect(await staff.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      expect(errors).toEqual([]);
      await staffContext.close();
    });
  }
}
