name: meta

on:
  push:
    paths: [.github/workflows/**]
  pull_request:
    paths: [.github/workflows/**]
  workflow_dispatch:

jobs:
  actionlint:
    name: lint workflows (actionlint)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Download actionlint
        run: bash <(curl -sSf https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - run: ./actionlint -color
